version: '3.7'
services:
  minio:
    image: minio/minio
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ACCESS_KEY: xWWXcCdvyNLlHGt2cwyC
      MINIO_SECRET_KEY: SZ69UCZBC5ycyV356Nv0
    command: server --console-address ":9001" /data

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add myminio http://minio:9000 xWWXcCdvyNLlHGt2cwyC SZ69UCZBC5ycyV356Nv0;
      /usr/bin/mc rm -r --force myminio/review-c;
      /usr/bin/mc mb myminio/review-c;
      /usr/bin/mc policy download myminio/review-c;
      exit 0;
      "

  db:
    container_name: db
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin'
      MYSQL_ROOT_PASSWORD: 'admin'
    ports:
      - '3306:3306'
    networks:
      - baratin
    volumes:
      - my-db:/var/lib/mysql
    extra_hosts:
      - 'docker.localhost:host-gateway'

volumes:
  my-db:
  minio_storage:

networks:
  baratin:
    name: baratin
