version: '3.7'
services:
  minio:
    image: minio/minio
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin
      MINIO_ACCESS_KEY: adminadmin
      MINIO_SECRET_KEY: admin
    command: server --console-address ":9001" /data

  db:
    container_name: db
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin'
      MYSQL_ROOT_PASSWORD: 'admin'
    ports:
      - '3306:3306'
    networks:
      - baratin
    volumes:
      - my-db:/var/lib/mysql
    extra_hosts:
      - 'docker.localhost:host-gateway'

volumes:
  my-db:
  minio_storage:

networks:
  baratin:
    name: baratin
