export const AWS_ACCESS_KEY_ID = 'AWS_ACCESS_KEY_ID'
export const AWS_SECRET_ACCESS_KEY = 'AWS_SECRET_ACCESS_KEY'
export const AWS_S3_BUCKET_NAME = 'AWS_S3_BUCKET_NAME'

export const AWS_S3_ENDPOINT = 'AWS_S3_ENDPOINT'

export const AWS_S3_REGION = 'AWS_S3_REGION'
